let info = {
    CountNearby: true,
    CustomerId: "0",
    HighlightedPlaceId: 0,
    IsADA: false,
    Latitude: 0,
    Longitude: 0,
    MinVehicleLength: 0,
    NearbyCountLimit: 10,
    NearbyLimit: 150,
    NearbyOnlyAvailable: false,
    Nights: "1",
    PlaceId: "28",
    RefreshFavourites: true,
    SleepingUnitId: 0,
    Sort: "Distance",
    StartDate: "04-19-2021",
    UnitCategoryId: 0,
    UnitTypesGroupIds: []
}